.gitignore, src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
(refs https://github.com/eslint/eslint/issues/8633#issuecomment-336941799)
=> Update: commit message checker to use status checks (fixes #11)

README.md
=> Docs: make readme more informative (fixes #24)

.eslintignore, .eslintrc.js, package.json, src/app.js, src/plugins/check-unit-test/index.js, src/plugins/commit-message/index.js, src/plugins/duplicate-comments/index.js, src/plugins/index.js, src/plugins/needs-info/index.js, src/plugins/pr-ready-to-merge/common.js, src/plugins/pr-ready-to-merge/index.js, src/plugins/pr-ready-to-merge/reviewCheck.js, src/plugins/pr-ready-to-merge/statusCheck.js, src/plugins/release-issues/index.js, src/plugins/triage/index.js, tests/.eslintrc.js, tests/plugins/check-unit-test/index.js, tests/plugins/commit-message/index.js, tests/plugins/duplicate-comments/index.js, tests/plugins/needs-info/index.js, tests/plugins/pr-ready-to-merge/index.js, tests/plugins/release-issues/index.js, tests/plugins/triage/index.js
This switches the codebase from `eslint-config-airbnb-base` to `eslint-config-eslint` to align with our other projects.
=> Chore: use eslint-config-eslint

package.json, src/app.js, src/plugins/index.js, src/plugins/release-merge-purifier/index.js, src/plugins/release-monitor/index.js, tests/plugins/release-monitor/index.js
Please review as I think I am done with coding and I have tested it with a test repo and app.
TODO:
=> New: Release monitor plugin (fixes #9)

src/plugins/release-monitor/index.js, tests/plugins/release-monitor/index.js
(refs https://github.com/eslint/eslint/pull/9763)
=> Update: rename "post-release" label to "patch release pending"

src/app.js, src/plugins/index.js, src/plugins/wip/index.js, tests/plugins/wip/index.js
~~Ironically, this is currently a WIP. I'm having issues with the tests where Nock seems to get confused depending on what tests are run. Probably that means I've misconfigured Nock and it's not being cleaned up between tests.~~
~~@gyandeeps @not-an-aardvark Any feedback on what I'm doing wrong in the tests?~~
This should be ready for review.
=> New: wip plugin (fixes #51)

.npmrc, package-lock.json
Since this is an application rather than a library, it should have a package-lock file.
=> Chore: add package-lock.json

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
refs https://github.com/eslint/eslint/issues/10427
=> Update: commit tag allowed `Revert`

README.md
Pretty self-explanatory, honestly.
=> Docs: Add info about WIP tracker to README

package-lock.json, package.json, src/app.js, src/plugins/recurring-issues/index.js, tests/plugins/check-unit-test/index.js, tests/plugins/commit-message/index.js, tests/plugins/duplicate-comments/index.js, tests/plugins/issue-archiver/index.js, tests/plugins/needs-info/index.js, tests/plugins/recurring-issues/index.js, tests/plugins/release-monitor/index.js, tests/plugins/triage/index.js, tests/plugins/wip/index.js
This updates probot to v7.1.2 and updates the codebase to account for some [breaking changes](https://github.com/probot/probot/releases/tag/v7.0.0) and deprecations.
=> Upgrade: probot to v7.1.2

CONTRIBUTING.md
This adds a `CONTRIBUTING.md` file with information on how to report issues.
=> Docs: add CONTRIBUTING.md

.travis.yml
Pretty self-explanatory, but please reach out with concerns.
Fixes #73.
=> Chore: Travis builds on all branches

package-lock.json, package.json
This upgrades `jest` to the latest version, which has the effect of fixing a security alert for a dependent package.
=> Upgrade: jest@23

.eslintrc.js, package-lock.json, package.json, src/plugins/check-unit-test/index.js, src/plugins/duplicate-comments/index.js, src/plugins/pr-ready-to-merge/reviewCheck.js, src/plugins/release-monitor/index.js, tests/__mocks__/probot-scheduler.js, tests/plugins/issue-archiver/index.js, tests/plugins/triage/index.js
* Upgrade a lot dependencies
* Most important upgrade was the `@octokit/rest`dependency of `probot`.
* Generated lock file again from scratch.
* Fix unit test
=> Upgrade: Various dependencies and fix unit test

src/plugins/auto-closer/index.js, tests/plugins/auto-closer/index.js
This fixes the auto-closer so it only works on issues.
=> Fix: Auto-closer should not be closing pull requests (refs #98)

src/plugins/auto-closer/index.js, tests/plugins/auto-closer/index.js
This changes the autoclose message so that questions get a comment that's more specific to the nature of the issue (asking them to contact the mailing list or chatroom for more information).
=> Update: Different message for autoclosing questions (fixes #105)

package-lock.json
This is the result of running `npm audit`. Note that it doesn't fix the `minimist` security vulnerabilities.
=> Upgrade: fix security vulnerabilities

package-lock.json, package.json
This should fix the current `minimist` security alert.
=> Upgrade: jest@26.1.0

package-lock.json, src/plugins/check-unit-test/index.js, src/plugins/commit-message/index.js, src/plugins/duplicate-comments/index.js, src/plugins/issue-archiver/index.js, src/plugins/recurring-issues/index.js, src/plugins/release-monitor/index.js, src/plugins/wip/index.js, tests/plugins/recurring-issues/index.js
This updates the location of the TSC meeting in the recurring issues.
Depends on https://github.com/eslint/website/pull/748 being merged.
=> Fix: Chat meeting location for TSC meetings

src/plugins/recurring-issues/index.js, tests/plugins/recurring-issues/index.js
Because running releases is quite involved, and there's a lot to remember to do, I thought adding some checklists to the autogenerated issue would be helpful. I know I have trouble remembering all of the steps, so hoping this will be helpful to everyone. Especially interested in feedback from @kaicataldo and @btmills are the main release-doers. :)
=> Update: Text in release issue

.github/workflows/deploy.yml
This changes the branch to watch from "master" to "main".
=> Chore: Update branch in deploy workflow

package.json
**Description:**
Add funding and homepage field
=> chore: add funding and homepage field

.github/workflows/ci.yml, .github/workflows/deploy.yml
**Description: **
Updated Github actions
=> ci: update Github actions

src/plugins/recurring-issues/index.js
Updates the release checklist to include the release of `@eslint/js` and the updating of `package.json`.
=> feat: Update release checklist

package-lock.json, package.json
https://github.com/eslint/eslint-github-bot/actions/runs/9040612044/job/24844988426
=> build: fix deploy error

package-lock.json, package.json
fixes https://github.com/eslint/eslint-github-bot/issues/210
=> fix: upgrade npm 10.x

.gitignore, eslint.config.js, package-lock.json, package.json
Hello,
In this PR, I've updated minor things in this repository.
1. I've added `*.vscode-workspace` and `.cursor` to `.gitignore`.
2. Bumped the version of `globals` and `eslint`.
3. Updated `eslint.config.js` to use `defineConfig` and `globalIgnores`.
=> chore: update `.gitignore` and `eslint.config.js`
