eslint/eslint-github-bot

src/plugins/check-unit-test/index.js
This adds some missing punctuation to the unit test checking comment.
=> Chore: improve grammar in unit test checking plugin

README.md
The app ID is a short (4-digit) number. Calling it an "Auth token" makes it sound like the ID is a secret value, but that's not the case.
=> Docs: clarify that APP_ID is not an auth code

package.json
This updates the `npm test` script to also run `npm run lint`.
=> Chore: run linter when running `npm test`

src/plugins/check-unit-test/index.js, src/plugins/duplicate-comments/index.js, src/plugins/needs-info/index.js, src/plugins/triage/index.js, tests/plugins/check-unit-test/index.js, tests/plugins/commit-message/index.js, tests/plugins/duplicate-comments/index.js, tests/plugins/needs-info/index.js, tests/plugins/triage/index.js
This updates all the plugins to return promises, rather than starting asynchronous events without listening for results. It also updates the tests to wait for those promises rather than waiting for a hardcoded delay.
=> Chore: remove race conditions and hardcoded timeouts

README.md, src/app.js
I want it to be as easy as possible to replace the current version of `eslintbot` with this bot, so this PR disables the experimental plugins by default so that we can replicate the current `eslintbot` behavior. I think we can reenable the experimental plugins after we resolve design issues like #15 and #22.
=> Update: disable experimental plugins by default

README.md, package.json, src/app.js, src/plugins/index.js, src/plugins/release-issues/index.js, tests/plugins/release-issues/index.js
Whenever an issue with the `release` label is closed for the first time, the bot parses a date out of the title and creates a new issue with the `release` label, the standard release issue text, and a date two weeks after the previous issue.
=> New: add release-issues plugin (refs #33)

src/plugins/recurring-issues/index.js, tests/plugins/recurring-issues/index.js
This fixes an issue where the response shape that the bot expected did
not match the response that GitHub actually returns. This caused the bot
to throw an error rather than posting a new TSC meeting issue earlier
today.
=> Fix: error when fetching team members for TSC meeting issue

src/plugins/triage/index.js, tests/plugins/triage/index.js
As suggested in https://github.com/eslint/eslint-github-bot/issues/38, this updates the bot to make an additional request to verify that an issue has no labels before adding the `triage` label.
=> Fix: avoid adding `triage` when an issue already has labels (fixes #38)

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
The `eslint.github.io` and `tsc-meeting` repositories don't have any releases, so it doesn't make sense to enforce the commit message check there.
=> Update: exclude some repositories from the commit message check

src/plugins/release-monitor/index.js
This updates the status check name for `release-monitor` to be in kebab-case, which is consistent with our other status checks (such as `commit-message` and the CI checks).
=> Chore: make status check capitalization consistent

src/plugins/release-monitor/index.js, tests/plugins/release-monitor/index.js
This updates status checks created by the `release-monitor` plugin to link to the pending release issue, to give the user a better idea about what the plugin is doing.
=> Update: make pending release-monitor status checks link to the release issue

src/plugins/release-monitor/index.js, tests/plugins/release-monitor/index.js
This updates the `release-monitor` status check to leave the correct success status on semver-patch PRs when entering post-release mode. This allows the plugin logic to be simpler, because the appropriate action for any given PR only depends on whether the repo is in post-release mode, and it doesn't depend on what triggered the current event.
=> Fix: make release-monitor statuses consistent (fixes #49)

README.md, package.json, src/app.js, src/plugins/index.js, src/plugins/issue-archiver/index.js, tests/plugins/issue-archiver/index.js
(fixes https://github.com/eslint/eslint/issues/9837)
This plugin does the following:
* Every 6 hours, the bot searches for issues which were closed more than 180 days ago and do not have the `"archived due to age"` label. It then locks all of these issues and adds the `"archived due to age"` label to each of them.
TODO:
=> New: add issue-archiver plugin

src/plugins/issue-archiver/index.js
I noticed this right after I merged #57. It doesn't make sense to run the issue archiver every 6 hours, because the search filter only has a resolution of 1 day anyway, so 3/4 of the runs would always find no new issues.
=> Chore: run issue-archiver once every 24 hours

src/plugins/triage/index.js, tests/plugins/triage/index.js
The bot is currently logging an error when a PR is opened, due to a bug in https://github.com/eslint/eslint-github-bot/pull/60.
```
TypeError: Cannot read property 'labels' of undefined
at triage (/path/to/eslint-github-bot/src/plugins/triage/index.js:15:31)
at EventEmitter.events.on (/path/to/eslint-github-bot/node_modules/probot/lib/robot.js:102:17)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
=> Fix: avoid error when a pull request is opened

src/plugins/release-monitor/index.js, tests/plugins/release-monitor/index.js
This updates the `release-monitor` plugin to paginate the pull requests that it sees, to ensure that it works correctly when there are more than 30 open pull requests. This also updates the tests for that plugin to only return one mock pull request at a time, to simulate paginated responses.
=> Fix: ensure release-monitor plugin paginates pull requests (fixes #67)

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
This is a first attempt at enforcing our issue reference guidelines in commit summaries (for single-commit PRs) and PR titles (for multiple-commit PRs).
Reference: https://eslint.org/docs/developer-guide/contributing/pull-requests#step2
Fixes #56.
Open to feedback on how things could be a little more readable-- unfortunately, readability suffered a bit when I was trying to fix some corner cases.
=> Update: commit-message enforces issue ref style (fixes #56)

.travis.yml
This updates Travis to (a) run Node 10, and (b) use `npm ci` when installing packages. The production environment also runs Node 10 and uses `npm ci`, so this should reduce the liklihood of errors from things like outdated `package-lock.json` files.
=> Chore: update CI to match production environment

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
Previously, if a PR had a single commit, and that commit's message spanned multiple lines, and the first line ended with (fixes #\<number\>), then the bot would report that the commit message didn't follow the guidelines because the issue reference wouldn't be at the "end" of the commit message. This updates the commit message checker to verify that issue references are at the end of the first line, rather than at the end of the entire commit message.
=> Fix: avoid reporting spurious for multiline commits referencing issues

src/plugins/wip/index.js, tests/plugins/wip/index.js
This fixes a typo where the WIP plugin is listening for `synchronized` events rather than `synchronize` events, which prevented the fix for #80 from working correctly. (For some reason, the webhook from GitHub is called [`synchronize`](https://developer.github.com/v3/activity/events/types/#events-api-payload-28) even though other webhook names are in past tense.)
=> Fix: typo in webhook name for WIP plugin (fixes #80)

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
=> Fix: skip other checks if commit message starts with 'Revert "' (fixes #89)

src/plugins/release-monitor/index.js, tests/plugins/release-monitor/index.js
Previously, the release monitor considered "Upgrade:" PRs to be semver-minor, even though `eslint-release` considers them to be semver-patch.
=> Fix: ensure "Upgrade:" PRs are considered semver-patch

package-lock.json, src/app.js, src/plugins/auto-closer/index.js, src/plugins/index.js, tests/plugins/auto-closer/index.js
This is the long-await auto-closer plugin for the bot. I initially wanted to look for issues who had the "accepted" label added 90 days ago, but it's hard to do that with the GitHub API, so I used activity level to approximate things.
This plugin auto closes:
* **accepted issues** if the issue has no assignee/project/milestone, was opened > 90 days ago and was last updated > 30 days ago.
* **unaccepted issues** if the issue has no assignee/project/milestone and was last updated > 30 days ago. (Our guidelines say unaccepted issues can be closed within 21 days, but it was easier to use 30 days for both queries. I don't think this makes much of a difference.)
This plugin does not have the "nag" feature originally referenced in #92 (to post a comment to remind assignees to work on the issue) …
=> New: auto-closer plugin (fixes #92)

README.md, src/plugins/auto-closer/index.js, tests/plugins/auto-closer/index.js
This fixes the "search query is too long" error described in #98. I fixed the code and added assertions to ensure that long search queries are caught.
=> Fix: Autocloser bot plugin error (refs #98)

src/plugins/auto-closer/index.js, tests/plugins/auto-closer/index.js
This update simply removes all blocked issues from consideration for auto-closing.
=> Update: Don't auto close blocked issues (fixes #104)

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
This PR fixes `commit-message` plugin to succeed with `(refs eslint/rfcs#22)`-like references.
=> Fix: commit-message failed on RFC refs

package-lock.json
`npm audit` currently reports 8461 vulnerabilities (2 moderate, 8459 high). This PR is the result of running `npm audit fix` and committing the lockfile changes.
=> Upgrade: update dependencies using npm audit fix

src/plugins/recurring-issues/index.js
Updating our release issue template to reflect [our decision to allow one person releases](https://github.com/eslint/tsc-meetings/blob/master/notes/2020/2020-02-27.md#release-cadence). This doesn't mean multiple can't run a release, but I think it makes sense to have the second person be additive.
=> Update: only require one volunteer when creating release issue

src/plugins/auto-closer/index.js
Fixes `auto-closer`'s comment for closed questions:
* The chatroom link will be now: `https://eslint.org/chat`
* Also adds a blank line before the hash, which should make it being hidden (as a link reference). It's currently visible, see [eslint/eslint#13418 (comment)](https://github.com/eslint/eslint/issues/13418#issuecomment-660562995)
=> Fix: change gitter link to discord link in auto-closer

src/plugins/commit-message/index.js, tests/plugins/commit-message/index.js
This PR updates `commit-message` to require a space after tag, per the [commit message format](https://eslint.org/docs/developer-guide/contributing/pull-requests#step-2-make-your-changes):
* `New:foo` is invalid
* `New: foo` is valid
=> Update: require space after "Tag:" in commit message

src/plugins/commit-message/createMessage.js, src/plugins/commit-message/index.js, tests/plugins/commit-message/__snapshots__/index.js.snap, tests/plugins/commit-message/index.js
Fixes #127, fixes #64
This change will comment on the PR with the errors and its details. 
- Currently, I am using snapshot testing for the assertion of the comment body, is it fine or do I need to change with the something which may be preferred by others?
- the error explanation is a hardcoded message. Mostly copied from the contribution guide. Should I add a script which will fetch from those source documents and write it to a file and from there we will use for the error details/explanation.
=> New: comment with the report for commit message (fixes #127)

.github/workflows/deploy.yml, README.md
I've deployed the bot to Dokku already, and this update creates a GitHub action that will automatically deploy to Dokku whenever a PR is merged to the master branch.
=> Chore: Move bot to Dokku and create auto-deploy workflow (fixes #109)

src/app.js, src/constants.js, src/plugins/add-to-triage-project/index.js, src/plugins/index.js, tests/plugins/add-to-triage-project/index.js
This change automatically adds new issues to the first column of the Triage project so we don't have to do it manually
First item in #136
=> New: Add new issues to triage project (refs #136)

src/plugins/add-to-triage-project/index.js, src/plugins/recurring-issues/index.js, tests/plugins/add-to-triage-project/index.js
I added a new "triage:no" label that the bot uses to determine not to include an issue on the triage board.
=> Update: Don't add auto-created issues to triage board (fixes #147)

src/plugins/needs-info/index.js, tests/plugins/needs-info/index.js
Changes the "needs info" label behavior so it doesn't autocomment, but instead, will comment when an issued is closed with the "needs info" label.
=> Update: needs info label behavior (refs #136)

src/plugins/commit-message/createMessage.js, src/plugins/commit-message/index.js, src/plugins/commit-message/util.js, tests/plugins/commit-message/__snapshots__/index.js.snap, tests/plugins/commit-message/index.js
This change ensures that pull requests will have appropriate tags added when the commit message is formatted correctly. Specifically:
* "feat" -> "feature"
* "feat!" -> "feature", "breaking"
* "fix" -> "bug"
* "fix!" -> "bug", "breaking"
* "chore" -> "chore"
* "build" -> "build"
* "test" -> "chore"
=> feat: Automatically add PR labels based on commit

.github/workflows/ci.yml
=> ci: use node v16

src/plugins/commit-message/index.js
Correct details URL for the commit message documentation from `master` to `main`
=> chore: change target URL from master -> main

package-lock.json, package.json, src/plugins/auto-closer/index.js, src/plugins/check-unit-test/index.js, src/plugins/commit-message/createMessage.js, src/plugins/commit-message/index.js, src/plugins/duplicate-comments/index.js, src/plugins/issue-archiver/index.js, src/plugins/needs-info/index.js, src/plugins/pr-ready-to-merge/common.js, src/plugins/pr-ready-to-merge/index.js, src/plugins/pr-ready-to-merge/reviewCheck.js, src/plugins/pr-ready-to-merge/statusCheck.js, src/plugins/recurring-issues/index.js, src/plugins/release-monitor/index.js, src/plugins/utils.js, src/plugins/wip/index.js, tests/plugins/add-to-triage-project/index.js, tests/plugins/auto-closer/index.js, tests/plugins/check-unit-test/index.js, tests/plugins/commit-message/index.js, tests/plugins/duplicate-comments/index.js, tests/plugins/issue-archiver/index.js, tests/plugins/needs-info/index.js, tests/plugins/recurring-issues/index.js, tests/plugins/release-monitor/index.js, tests/plugins/triage/index.js, tests/plugins/wip/index.js
Alternative to dependabot's automatic `eslint` upgrade in #157. I upgraded to the latest `eslint`, `eslint-config-eslint`, and `eslint-config-node`. I upgraded to the last version of `lint-staged` that still supports Node 12 so this is still a semver-patch change.
Review this one commit at a time. I separated out fixes for each new category of lint report into individual commits.
=> chore: Upgrade linting

src/plugins/recurring-issues/index.js
Once https://github.com/eslint/eslint/pull/16130 is merged, release blog posts will be unpublished drafts by default and only published once the releaser adds the highlights.
=> chore: Update release instructions for draft blog posts

.github/workflows/deploy.yml
As best I can tell from the [docs](https://github.com/dokku/github-action#inputs), this seems like the fix to make the bot deploy to the correct branch.
Fixes #192
=> chore: Fix deploy workflow

src/plugins/recurring-issues/index.js
This PR changes the Jenkins URL in the body of new release issues to https://jenkins2.eslint.org.
=> fix: update Jenkins URL in release issue body

src/plugins/recurring-issues/index.js
As noted during the last release, it makes more sense to release `@eslint/js` after any other packages just before `eslint`, because `eslint` and `@eslint/js` should have the same version number.
=> fix: move `@eslint/js` release after other packages

package.json
As a temporary measure to get us up and running again, I'm pinning our supported Node.js version to 16.x. I think this should get us deploying again until we can do #205
=> build: Pin to Node.js 16.x

eslint.config.js, tests/.eslintrc.js
Removes now unused `tests/.eslintrc.js` file.
Also updates `eslint.config.js` to separate configs for this file and test files.
=> chore: remove `.eslintrc.js` file

.gitignore, README.md, package.json, src/app.js
This pull request includes updates to the `package.json` file and significant refactoring of the `src/app.js` file to streamline the code and improve maintainability. The most important changes include adding a new engine requirement, removing unused imports and environment variable checks, and refactoring the plugin loading mechanism.
For some reason, Dokku was downgrading npm to v5.x when it saw `package-lock.json`, so hardcoding that in `package.json` is necessary. The rest is just cleanup using the new Probot APIs.
Updates to dependencies:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L57-R58): Added a new engine requirement for `npm` version 10.x.
Refactoring:
* [`src/app.js`](diffhunk://#diff-c72a907ac323cd2f334ed0e2bd07d15ab62581 …
=> fix: Add npm version and fix app setup

README.md
Before upgrading Probot, we had our webhooks URL as `/`; now it uses the default, so documenting that in the README for safekeeping.
=> docs: Update README with webhook URL

eslint.config.js, package-lock.json, package.json, src/plugins/commit-message/index.js, src/plugins/release-monitor/index.js, src/plugins/wip/index.js
Upgrades to latest eslint v9, and latest eslint-config-eslint v11 (which is now possible since the bot runs in Node 22 where new syntax and language features that config enforces are available).
=> refactor: switch to eslint v9, eslint-config-eslint v11

src/app.js, src/plugins/auto-assign/index.js, src/plugins/index.js, tests/plugins/auto-assign/index.js
This PR adds a new plugin that automatically assigns issues to users who have checked the "I am willing to submit a pull request to implement this change" checkbox in the issue template.
Closes #218
=> feat: automatically assign issues to users willing to submit PRs

.github/copilot-instructions.md, src/constants.js
In this PR, I've removed the unused `constants` file.
After reviewing the entire codebase, it looks like the `constants` file isn't referenced anywhere, so I've decided to remove it.
According to the git history, the last time this file was used was about three years ago, so I think it's safe to delete it.
In this PR, I've removed the unused `constants` file.
N/A
N/A
=> chore: remove unused `constants` file
